#driver=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://127.0.0.1:3306/scoula_db
jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mysql://localhost:3306/scoula_db
jdbc.username=scoula
jdbc.password=1234

# --- 파일 업로드 설정 (여기에 새로 추가) ---
file.upload.location=/Users/guhyeseong/upload
file.upload.max-file-size=10485760
file.upload.max-request-size=20971520
file.upload.file-size-threshold=5242880